"""Deterministic verification of model-supplied evidence."""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from judgment import JudgeResult
from model import Decision
from policies import GateAction
from policy_retrieval import PolicyMatch


class VerificationResult(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    valid: bool
    checked_claims: int
    errors: list[str]


def evidence_source_catalog(
    decision: Decision,
    policies: list[PolicyMatch],
) -> dict[str, dict[str, object]]:
    """Build the exact evidence-source allowlist supplied to the judge.

    Source IDs are generated by trusted application code. The model may cite
    these IDs, but it cannot create new evidence categories or silently treat
    an uncited assertion as verified evidence.
    """

    ci_status = (
        "passed"
        if decision.ci_passed is True
        else "failed"
        if decision.ci_passed is False
        else "unknown"
    )
    catalog: dict[str, dict[str, object]] = {
        "pr:title": {
            "kind": "pull_request_metadata",
            "title": decision.title,
        },
        "ci:prerequisite": {
            "kind": "continuous_integration",
            "status": ci_status,
        },
        "diff:summary": {
            "kind": "diff_metadata",
            "complete": decision.diff_complete,
            "changed_lines": decision.diff_lines,
        },
        "pr:reversibility": {
            "kind": "pull_request_metadata",
            "reversible": decision.reversible,
        },
        "pr:incident-linkage": {
            "kind": "pull_request_metadata",
            "touches_incident_code": decision.touches_incident_code,
        },
    }
    for path in decision.files_touched:
        catalog[f"file:{path}"] = {
            "kind": "changed_file",
            "path": path,
        }
    for policy in policies:
        catalog[f"policy:{policy.policy_id}"] = {
            "kind": "retrieved_policy",
            "policy_id": policy.policy_id,
            "title": policy.title,
        }
    return catalog


def verify_judgment(
    decision: Decision,
    policies: list[PolicyMatch],
    judgment: JudgeResult,
) -> VerificationResult:
    available_sources = evidence_source_catalog(decision, policies)
    available_policies = {policy.policy_id for policy in policies}
    errors: list[str] = []

    for policy_id in judgment.triggered_policies:
        if policy_id not in available_policies:
            errors.append(f"Policy {policy_id} was not retrieved.")

    for citation in judgment.evidence:
        for source_id in citation.source_ids:
            if source_id not in available_sources:
                errors.append(f"Evidence source was not supplied: {source_id}")

    if judgment.action != GateAction.AUTO_MERGE_CANDIDATE and not judgment.evidence:
        errors.append("A restrictive decision must contain verifiable evidence.")

    return VerificationResult(
        valid=not errors,
        checked_claims=len(judgment.evidence),
        errors=errors,
    )
